---
- name: Install tomcat
  become: yes
  hosts: appserver
  vars:
    - username: tomcat
    - home_dir: /opt/tomcat
    - default_shell: /bin/false
  tasks:
    - name: update apt repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
      when: ansible_facts['os_family'] == "Debian"
    - name: install openjdk 11
      package:
        name: "{{java_package}}"
        state: present 
    - name: creating a tomcat user
      ansible.builtin.user:
        creat_home: yes
        group: "{{username}}"
        home: "{{home_dir}}"
        name: "{{username}}"
        shell: "{{default_shell}}"
        state: present
      when: ansible_facts['os_family'] == "Debian"
        