---
- name: Install Nodejs and NPM
  become: yes
  hosts: all
  tasks: 
   - name: install nodejs 
     ansible.builtin.apt:
      name: install nodejs
      update_cache: true
   - name: install npm
     ansible.builtin.apt:
      name: install npm
      update_cache: true


